const tools=[
 {name:'ChatGPT',code:'GPT',tone:'emerald',use:'Escrita, estratégia e planejamento',url:'https://chatgpt.com',skills:['E-book completo','Pesquisa de público','Oferta','Calendário editorial','Página de vendas','Roteiro para Reels','Prospecção','Plano de negócios','Organização financeira','Revisão estratégica']},
 {name:'Claude',code:'CL',tone:'sand',use:'Análise e documentos longos',url:'https://claude.ai',skills:['Manual aprofundado','Análise de concorrentes','Revisão de e-book','Estrutura de curso','Documentação','Escopo comercial','Estudo de caso','Plano trimestral','Atendimento','Auditoria de conteúdo']},
 {name:'Gemini',code:'GE',tone:'blue',use:'Pesquisa e ecossistema Google',url:'https://gemini.google.com',skills:['Pesquisa de mercado','Organização de informações','Ideias de produtos','Plano de estudos','Comparação','Palavras-chave','Planejamento semanal','Oportunidades','Guia iniciante','Estratégia digital']},
 {name:'Canva',code:'CA',tone:'violet',use:'Design e apresentação',url:'https://canva.com',skills:['Capa de e-book','Carrossel','Identidade visual','Apresentação','Post','Stories','Portfólio','Boas-vindas','Infográfico','Página visual']},
 {name:'CapCut',code:'CC',tone:'silver',use:'Vídeos e anúncios',url:'https://capcut.com',skills:['Reel com gancho','Anúncio','Depoimento','Tutorial','Legenda','Comparação','Bastidores','TikTok','Vitrine','Lançamento']},
 {name:'Runway',code:'RW',tone:'magenta',use:'Geração e edição de vídeo',url:'https://runwayml.com',skills:['Vídeo publicitário','Cena','Demonstração','Transição','Animação','Conceito','B-roll','Marca','Campanha','Storyboard']},
 {name:'ElevenLabs',code:'EL',tone:'amber',use:'Narração, voz e áudio',url:'https://elevenlabs.io',skills:['Narração','Tutorial','Podcast','Audiobook','Locução','Institucional','Reels','Guia em áudio','Pausas','Voz de marca']},
 {name:'Perplexity',code:'PX',tone:'cyan',use:'Pesquisa com referências',url:'https://perplexity.ai',skills:['Pesquisa com fontes','Validação','Tendências','Concorrentes','Dúvidas','Verificação','Preços','Público','Oportunidades','Referências']},
 {name:'Gamma',code:'GA',tone:'lime',use:'Apresentações e páginas',url:'https://gamma.app',skills:['E-book visual','Apresentação','Proposta','Treinamento','Portfólio','Manual','Pitch','Relatório','Guia','Produto']},
 {name:'Midjourney',code:'MJ',tone:'mono',use:'Imagens e conceitos visuais',url:'https://midjourney.com',skills:['Capa editorial','Campanha','Retrato','Produto','Marca','Cena','Mockup','Ilustração','Conceito','Criativo']},
 {name:'Pika Free',code:'PK',tone:'cyan',use:'Vídeos curtos com créditos gratuitos',url:'https://pika.art',plan:'GRÁTIS · 80 CRÉDITOS/MÊS',videoProfile:'pika',skills:['Anúncio vertical dinâmico','Produto ganhando movimento','Transformação visual rápida','Cena para TikTok','Pikaffect chamativo','Imagem transformada em vídeo','Troca criativa de elemento','Sequência de três cenas','Gancho visual imediato','Loop curto contínuo']},
 {name:'Luma Ray Plus',code:'LR',tone:'amber',use:'Vídeos cinematográficos em plano pago',url:'https://lumalabs.ai/ray',plan:'PAGO · PRODUÇÃO PROFISSIONAL',videoProfile:'luma',skills:['Comercial cinematográfico','Movimento de câmera controlado','Continuidade entre tomadas','Cena realista de produto','Atmosfera de marca','Plano-sequência publicitário','Transição cinematográfica','Imagem para vídeo premium','Campanha com várias cenas','Encerramento visual de alto nível']}
];
const audiences=['iniciantes','profissionais autônomos','negócios locais','criadores de conteúdo','prestadores de serviços','comerciantes','estudantes','empreendedores digitais','consultores','equipes em crescimento'];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function promptTitle(tool,i){return `${tool.skills[i%10]} para ${audiences[Math.floor(i/10)]}`}
function prompt(tool,i){
 const title=promptTitle(tool,i),audience=audiences[Math.floor(i/10)],skill=tool.skills[i%10],scenario=(i%10)+1;
 if(tool.videoProfile)return videoPrompt(tool,i,title,audience,skill,scenario);
 const modes=['estratégico','didático','analítico','criativo','operacional','comparativo','editorial','comercial','visual','técnico'];
 const formats=['plano de ação','documento estruturado','guia prático','matriz de decisão','roteiro completo','manual operacional','projeto em etapas','modelo editável','relatório aplicado','sistema de execução'];
 const lines=[
 `PROMPT ${String(i+1).padStart(3,'0')} — ${title.toUpperCase()}`,
 `FERRAMENTA PRINCIPAL: ${tool.name}`,
 `ESPECIALIDADE DESTA TAREFA: ${tool.use}`,
 `MODO DE TRABALHO: ${modes[i%10]}`,
 `FORMATO PRINCIPAL: ${formats[Math.floor(i/10)%10]}`,
 `CENÁRIO EXCLUSIVO: ${scenario}.${Math.floor(i/10)+1}`,
 `PÚBLICO DE REFERÊNCIA: ${audience}`,
 '',
 'PAPEL E RESPONSABILIDADE',
 `1. Atue como especialista sênior em ${skill.toLowerCase()} utilizando os recursos mais adequados do ${tool.name}.`,
 `2. Conduza o projeto “${title}” com raciocínio ${modes[i%10]}, linguagem clara e decisões justificadas.`,
 `3. Considere que o usuário deseja uma entrega prática para ${audience}, e não uma explicação genérica.`,
 `4. Não comece produzindo a resposta final antes de compreender objetivo, contexto, restrições e materiais disponíveis.`,
 `5. Identifique informações ausentes e nunca preencha dados importantes com suposições apresentadas como fatos.`,
 '',
 'INFORMAÇÕES QUE O USUÁRIO DEVE PREENCHER',
 `6. Objetivo principal do projeto: [DESCREVA O RESULTADO DESEJADO PARA ${title.toUpperCase()}].`,
 `7. Público específico: [IDADE OU PERFIL, NÍVEL DE EXPERIÊNCIA, CONTEXTO E NECESSIDADE].`,
 `8. Problema observado: [SITUAÇÃO REAL QUE PRECISA SER MELHORADA].`,
 `9. Material já disponível: [TEXTOS, DADOS, LINKS, EXEMPLOS, IDENTIDADE OU RASCUNHOS].`,
 `10. Restrições: [PRAZO, ORÇAMENTO, FERRAMENTAS, TAMANHO, CANAL E FORMATO].`,
 `11. Tom desejado: [PROFISSIONAL, DIRETO, ACOLHEDOR, TÉCNICO OU OUTRO].`,
 `12. Critério de sucesso: [COMO SERÁ POSSÍVEL VERIFICAR QUE A ENTREGA FICOU BOA].`,
 '',
 'DIAGNÓSTICO OBRIGATÓRIO',
 `13. Faça seis perguntas objetivas e personalizadas sobre ${skill.toLowerCase()} antes de desenvolver a solução.`,
 `14. Pergunte qual ação o público ${audience} deverá conseguir concluir depois de usar a entrega.`,
 `15. Pergunte quais tentativas anteriores já foram feitas e por que não resolveram o problema.`,
 `16. Pergunte quais referências visuais, textuais ou técnicas devem ser consideradas ou evitadas.`,
 `17. Pergunte o que obrigatoriamente precisa aparecer e o que não pode fazer parte do resultado.`,
 `18. Pergunte como o usuário pretende revisar, publicar, apresentar ou testar a entrega final.`,
 `19. Aguarde as respostas quando elas forem essenciais; se o usuário pedir um rascunho, marque claramente cada hipótese.`,
 '',
 'ANÁLISE E PLANEJAMENTO',
 `20. Resuma o pedido em uma frase específica, citando ${title}, o público e o resultado esperado.`,
 `21. Separe fatos confirmados, preferências, limitações, hipóteses e decisões ainda pendentes.`,
 `22. Identifique o principal risco de produzir ${skill.toLowerCase()} sem dados suficientes.`,
 `23. Apresente três abordagens diferentes para o cenário ${scenario}.${Math.floor(i/10)+1}.`,
 `24. Compare as abordagens por clareza, esforço, custo, tempo, facilidade de aplicação e possibilidade de revisão.`,
 `25. Recomende uma abordagem e explique por que ela combina com ${audience}.`,
 `26. Divida o trabalho em preparação, primeira versão, revisão, teste e entrega.`,
 `27. Defina o resultado verificável de cada etapa antes de começar a execução.`,
 '',
 'EXECUÇÃO DETALHADA',
 `28. Construa primeiro a estrutura completa do ${formats[Math.floor(i/10)%10]} antes de escrever os detalhes.`,
 `29. Organize a estrutura em seções numeradas, cada uma com objetivo, entrada necessária e saída esperada.`,
 `30. Desenvolva a primeira seção de ${title} usando informações concretas fornecidas pelo usuário.`,
 `31. Desenvolva a segunda seção conectando problema, público e resultado sem repetir a seção anterior.`,
 `32. Desenvolva a terceira seção com um passo a passo executável e verbos de ação específicos.`,
 `33. Desenvolva a quarta seção incluindo critérios para escolher, adaptar ou descartar alternativas.`,
 `34. Desenvolva a quinta seção mostrando como verificar o trabalho dentro do ${tool.name}.`,
 `35. Acrescente uma etapa de personalização para impedir que o resultado pareça um modelo genérico.`,
 `36. Inclua um exemplo totalmente preenchido relacionado a ${audience} e ao cenário ${scenario}.${Math.floor(i/10)+1}.`,
 `37. Depois do exemplo, forneça uma versão editável com campos entre colchetes e instruções de preenchimento.`,
 `38. Crie uma variação curta, uma intermediária e uma completa da mesma solução.`,
 `39. Explique quando cada variação deve ser utilizada e qual é a limitação de cada uma.`,
 `40. Use títulos informativos, parágrafos curtos, listas úteis e hierarquia fácil de consultar.`,
 '',
 `ORIENTAÇÕES ESPECÍFICAS PARA ${tool.name.toUpperCase()}`,
 `41. Explore a capacidade de ${tool.name} ligada a ${tool.use.toLowerCase()}, sem atribuir funções que a ferramenta não possui.`,
 `42. Quando houver texto longo, mantenha termos, objetivos e decisões consistentes entre todas as seções.`,
 `43. Quando houver criação visual ou audiovisual, descreva composição, ritmo, enquadramento, contraste e legibilidade.`,
 `44. Quando houver pesquisa, diferencie descoberta inicial, fonte verificável, interpretação e conclusão.`,
 `45. Quando houver dados, mostre o cálculo, a origem ou a regra utilizada e sinalize qualquer incerteza.`,
 `46. Quando houver comunicação comercial, apresente valor com clareza sem inventar resultados, depoimentos ou escassez.`,
 '',
 'CONTROLE DE QUALIDADE',
 `47. Revise se cada parte realmente contribui para ${title} e elimine trechos genéricos ou repetidos.`,
 `48. Verifique se o vocabulário está adequado ao nível de experiência de ${audience}.`,
 `49. Procure contradições entre objetivo, instruções, exemplo, formato e chamada para ação.`,
 `50. Confirme se nomes, números, links e informações factuais foram fornecidos ou marcados para verificação.`,
 `51. Avalie a entrega de zero a dez em clareza, profundidade, aplicabilidade, originalidade e acabamento.`,
 `52. Para qualquer critério abaixo de oito, faça uma revisão específica antes de apresentar o resultado.`,
 `53. Crie uma checklist final com pelo menos dez verificações próprias para ${skill.toLowerCase()}.`,
 '',
 'FORMATO DA RESPOSTA FINAL',
 `54. Comece com um resumo executivo de até seis linhas explicando o que será entregue e por quê.`,
 `55. Apresente em seguida o diagnóstico, as decisões tomadas e as informações que ainda precisam de confirmação.`,
 `56. Entregue o ${formats[Math.floor(i/10)%10]} completo, pronto para copiar, editar ou aplicar.`,
 `57. Mostre o exemplo preenchido separado do modelo editável para evitar confusão.`,
 `58. Inclua a checklist de qualidade e um plano de teste compatível com ${audience}.`,
 `59. Termine com três próximos passos ordenados por prioridade, esforço e impacto esperado.`,
 `60. Faça uma pergunta final específica que permita melhorar a próxima versão de ${title}.`,
 '',
 'COMANDO DE INÍCIO',
 `Antes de executar, confirme que entendeu este projeto de ${title} e apresente as seis perguntas do diagnóstico.`
 ];
 return distinctPrompt(tool,title,audience,skill,scenario,i);
}
function videoPrompt(tool,i,title,audience,skill,scenario){
 const pika=tool.videoProfile==='pika',aspect=['9:16','16:9','1:1'][i%3],duration=pika?`${3+i%3} segundos`:`${5+(i%2)*5} segundos`,number=String(i+1).padStart(3,'0');
 const lines=[
  pika?`Converta “${title}” em um vídeo curto exclusivo no Pika para ${audience}.`:`Dirija “${title}” como uma produção cinematográfica exclusiva no Luma Ray para ${audience}.`,
  `Identifique este trabalho como projeto audiovisual ${number}, no formato ${aspect} e com duração de ${duration}.`,
  `Explore ${skill.toLowerCase()} sem imitar obras, personagens, marcas ou estilos protegidos.`,
  pika?'Priorize impacto instantâneo, transformação legível e movimento adequado à tela do celular.':'Priorize continuidade física, composição cinematográfica, luz realista e câmera controlada.',
  pika?'Utilize apenas um efeito principal do Pika para manter a mensagem clara.':'Utilize os controles do Ray para manter sujeito, cenário e direção de movimento consistentes.',
  'Defina o objetivo observável do vídeo em uma única frase.',
  'Descreva completamente o sujeito ou produto principal.',
  'Informe quais características visuais precisam permanecer inalteradas.',
  'Determine o ambiente, horário, clima e materiais presentes na cena.',
  'Escolha uma paleta coerente com a identidade da marca.',
  'Indique o resultado emocional esperado sem usar promessas exageradas.',
  'Reserve uma área vazia para texto que será acrescentado somente na edição.',
  'Planeje um único acontecimento central compatível com a duração.',
  'Descreva o primeiro quadro com posição, escala e direção do sujeito.',
  'Estabeleça o ponto de atenção percebido no primeiro segundo.',
  'Explique o estado inicial antes de qualquer transformação ou deslocamento.',
  'Defina a ação principal com direção, velocidade e aceleração.',
  'Descreva como objetos secundários reagem ao movimento principal.',
  'Mantenha anatomia, proporções, embalagem e detalhes estáveis.',
  'Evite elementos duplicados, rostos alterados e objetos que desapareçam.',
  'Escolha câmera fixa, panorâmica, travelling, órbita ou dolly.',
  'Não misture movimentos de câmera incompatíveis na mesma tomada.',
  'Informe a lente visual e a profundidade de campo desejadas.',
  'Determine se a câmera acompanha, revela ou antecipa a ação.',
  'Descreva a fonte, a direção e a temperatura da luz principal.',
  'Acrescente preenchimento somente quando ele preservar detalhes importantes.',
  'Faça reflexos e sombras acompanharem corretamente cada movimento.',
  'Mantenha cores e exposição constantes durante toda a geração.',
  'Defina o acabamento como realista, publicitário, gráfico ou experimental.',
  'Especifique textura, contraste e saturação sem citar artistas vivos.',
  'Faça o fundo apoiar a mensagem sem competir com o elemento principal.',
  pika?'Mostre claramente o estado anterior, a mudança e o resultado da transformação.':'Construa entrada, desenvolvimento visual e composição final estável.',
  pika?'Garanta que o clipe funcione mesmo quando assistido sem áudio.':'Prepare espaço de ritmo para receber narração e design sonoro posteriormente.',
  'Planeje o quadro final para permanecer legível por pelo menos meio segundo.',
  'Evite terminar com movimento interrompido ou corte aparentemente acidental.',
  'Quando houver loop, conecte posição, luz e velocidade do final ao começo.',
  'Quando não houver loop, encerre com composição adequada à chamada para ação.',
  'Gere primeiro uma versão-base sem palavras, logotipos inventados ou legendas.',
  'Analise a versão-base quadro a quadro antes de solicitar outra geração.',
  'Confirme que o sujeito permanece reconhecível durante todo o clipe.',
  'Confirme que nenhum elemento aparece ou desaparece sem motivo visual.',
  'Confirme que a câmera mantém a direção estabelecida.',
  'Confirme que sombras e reflexos obedecem à iluminação escolhida.',
  'Confirme que a área reservada para texto continua desocupada.',
  `Confirme que o enquadramento ${aspect} não corta informações essenciais.`,
  'Identifique o segundo exato em que a cena perde clareza ou estabilidade.',
  'Corrija somente o problema encontrado antes de mudar toda a ideia.',
  'Produza uma variação alterando apenas câmera, velocidade ou iluminação.',
  'Mantenha os demais elementos iguais para permitir comparação justa.',
  'Compare versões por clareza, estabilidade, impacto, naturalidade e acabamento.',
  `Escolha a versão mais compreensível para ${audience}.`,
  'Não escolha uma versão apenas por possuir mais efeitos ou movimento.',
  'Registre qual decisão tornou a versão escolhida superior.',
  'Prepare o prompt positivo final como um único bloco contínuo.',
  'Comece o bloco identificando sujeito, ação e ambiente.',
  'Continue detalhando composição, câmera, lente e deslocamento.',
  'Depois descreva iluminação, paleta, textura e realismo.',
  'Finalize informando duração, proporção, estabilidade e quadro final.',
  'Crie uma lista negativa curta com as falhas que precisam ser evitadas.',
  'Não escreva comandos contraditórios nos blocos positivo e negativo.',
  `Não inclua falas longas em uma geração de apenas ${duration}.`,
  'Não dependa de letras geradas pela IA dentro da imagem.',
  'Não use imagens de pessoas reais sem autorização adequada.',
  'Não invente depoimentos, resultados comerciais ou provas de venda.',
  'Não reproduza interfaces e notificações como se fossem acontecimentos reais.',
  'Não solicite música protegida; descreva somente ritmo e atmosfera.',
  'Sugira três camadas sonoras: ambiente, ação e impacto final.',
  'Indique onde a narração pode entrar sem competir com a cena.',
  'Crie uma legenda curta para ser adicionada na edição externa.',
  'Crie uma chamada para ação verdadeira e compatível com o objetivo.',
  'Explique a melhor configuração de exportação para celular.',
  `Verifique novamente resolução, duração e proporção ${aspect}.`,
  'Assista uma vez sem som para testar a compreensão visual.',
  'Assista com som para conferir ritmo e sincronização.',
  `Mostre a versão a uma pessoa do público ${audience} e registre a interpretação.`,
  'Se a interpretação estiver errada, corrija primeiro a abertura.',
  'Entregue prompt positivo, lista negativa, áudio e legenda em blocos separados.',
  `Mostre ${aspect} e ${duration} no bloco de configuração.`,
  'Justifique brevemente a câmera, a luz e o ritmo selecionados.',
  'Apresente a variação sem copiar palavra por palavra o prompt principal.',
  `Finalize com uma checklist criada especificamente para “${title}”.`,
  'Inclua estabilidade, legibilidade, continuidade e direitos de uso na checklist.',
  'Não transforme a resposta em questionário nem interrompa a produção.',
  `Não numere estas instruções no texto que será colado no ${tool.name}.`,
  `Comece diretamente pelo conceito visual exclusivo do projeto ${number}.`,
  'Encerre somente depois de entregar todos os blocos prontos para geração e revisão.'
 ];
 return lines.join('\n');
}
function continuousPrompt(tool,title,audience,skill,scenario,i){
 const subject=skill.toLowerCase(),name=tool.name,context=`${audience} no cenário ${scenario}.${Math.floor(i/10)+1}`;
 const toolIndex=Math.max(0,tools.indexOf(tool)),globalIndex=toolIndex*100+i;
 const openings=[
  'Assuma a direção criativa e desenvolva','Construa do zero, com profundidade,','Transforme conhecimento especializado em','Conduza uma produção profissional de','Elabore com atenção aos detalhes','Projete uma solução completa de','Dê forma a uma versão avançada de','Estruture cuidadosamente','Produza uma entrega original de','Modele uma experiência prática de',
  'Atue como responsável principal pela criação de','Prepare uma execução detalhada de','Converta este objetivo em','Desenvolva uma solução utilizável de','Organize uma produção consistente de','Crie, revise e finalize','Planeje e entregue com qualidade','Materialize uma proposta completa de','Componha uma versão profissional de','Construa uma referência prática de',
  'Inicie uma criação aprofundada de','Realize uma produção original de','Desenhe uma solução clara de','Monte uma entrega pronta de','Apresente uma abordagem completa para','Desenvolva uma experiência guiada de','Consolide uma solução de alta qualidade para','Prepare uma versão aplicável de','Transforme a seguinte finalidade em','Execute com rigor a criação de',
  'Idealize e desenvolva','Demonstre domínio técnico ao criar','Organize com precisão','Crie uma resposta definitiva para','Produza com linguagem natural','Desenvolva com visão estratégica','Construa com foco no usuário','Prepare com acabamento profissional','Elabore uma solução autoral de','Conduza com clareza a criação de'
 ];
 const opening=`${openings[globalIndex%openings.length]} ${title.toLowerCase()} no ${name}, direcionado a ${context}.`;
 return [
 opening,
 `Produza uma entrega completa, aprofundada, profissional e imediatamente utilizável por ${audience}.`,
 `Assuma a função de especialista experiente em ${subject} e conduza todo o trabalho do começo ao fim.`,
 `Escreva com segurança, clareza e domínio técnico, sem parecer um texto automático ou superficial.`,
 `Mantenha o foco absoluto em ${title.toLowerCase()} durante toda a criação.`,
 `Considere as necessidades reais de ${context} ao tomar cada decisão.`,
 `Crie uma abertura forte que explique de maneira simples o que será construído.`,
 `Apresente o objetivo da entrega sem exageros, frases vazias ou promessas impossíveis.`,
 `Mostre por que ${subject} é importante para esse público e para esse contexto.`,
 `Organize o conteúdo em uma sequência lógica que uma pessoa iniciante consiga acompanhar.`,
 `Comece pelos fundamentos necessários para compreender o assunto sem depender de outro material.`,
 `Explique cada conceito com linguagem direta antes de avançar para uma parte mais complexa.`,
 `Transforme conceitos abstratos em orientações concretas e fáceis de visualizar.`,
 `Use exemplos realistas relacionados a ${audience} em vez de situações genéricas.`,
 `Mostre uma situação inicial comum que revele o problema que será resolvido.`,
 `Apresente o resultado desejado de forma observável e compreensível.`,
 `Crie uma estrutura central própria para ${title.toLowerCase()} e mantenha essa estrutura consistente.`,
 `Divida o desenvolvimento em partes que se conectem naturalmente umas às outras.`,
 `Faça cada parte acrescentar uma informação nova e evite repetir orientações já apresentadas.`,
 `Explique o que deve ser preparado antes de iniciar a execução prática.`,
 `Liste os recursos realmente necessários sem adicionar ferramentas apenas para aumentar o conteúdo.`,
 `Apresente alternativas simples quando algum recurso principal não estiver disponível.`,
 `Descreva a primeira ação de maneira detalhada e mostre exatamente como realizá-la.`,
 `Descreva a segunda ação como uma continuação natural do resultado obtido anteriormente.`,
 `Descreva a terceira ação acrescentando profundidade e aplicação prática.`,
 `Descreva a quarta ação demonstrando como adaptar o trabalho ao público definido.`,
 `Descreva a quinta ação mostrando como transformar a ideia em uma versão utilizável.`,
 `Descreva a sexta ação explicando como revisar o que foi produzido.`,
 `Descreva a sétima ação mostrando como identificar e corrigir pontos fracos.`,
 `Descreva a oitava ação preparando a entrega para apresentação, publicação ou utilização.`,
 `Inclua detalhes próprios de ${name} que realmente contribuam para ${subject}.`,
 `Explique como aproveitar as funções do ${name} sem atribuir à ferramenta recursos que ela não possui.`,
 `Mantenha termos, estilo, objetivo e decisões coerentes em todas as partes da resposta.`,
 `Produza um exemplo completo relacionado a ${context}.`,
 `Faça o exemplo parecer um trabalho real e não apenas uma demonstração com frases genéricas.`,
 `Mostre o exemplo desde a ideia inicial até a versão pronta.`,
 `Explique por que cada decisão do exemplo foi tomada.`,
 `Mostre como uma escolha diferente alteraria o resultado final.`,
 `Crie uma segunda variação do exemplo com abordagem e linguagem diferentes.`,
 `Faça a segunda variação atender ao mesmo objetivo sem copiar a estrutura da primeira palavra por palavra.`,
 `Compare as duas variações e explique em qual situação cada uma funciona melhor.`,
 `Inclua orientações de personalização para que o resultado tenha identidade própria.`,
 `Evite clichês, introduções previsíveis e expressões que poderiam servir para qualquer assunto.`,
 `Prefira verbos específicos e instruções que possam ser colocadas em prática.`,
 `Evite respostas curtas onde uma explicação detalhada for necessária.`,
 `Evite aumentar o texto repetindo a mesma ideia com palavras diferentes.`,
 `Mantenha parágrafos legíveis e uma progressão agradável entre as ideias.`,
 `Use títulos internos somente quando ajudarem a pessoa a encontrar uma parte da entrega final.`,
 `Faça os títulos internos descreverem o conteúdo, sem usar nomes vagos como parte um ou continuação.`,
 `Inclua observações técnicas importantes para evitar erros durante a aplicação.`,
 `Mostre os erros mais comuns relacionados a ${subject} e como corrigi-los.`,
 `Explique por que cada erro prejudica a qualidade, a clareza ou a utilização do resultado.`,
 `Apresente uma versão inicial que possa ser produzida com poucos recursos.`,
 `Apresente uma versão intermediária com acabamento e profundidade maiores.`,
 `Apresente uma versão avançada adequada a uma entrega profissional.`,
 `Diferencie claramente o que muda entre as três versões.`,
 `Mostre qual versão é mais adequada para ${audience} neste cenário.`,
 `Inclua critérios claros para avaliar se ${title.toLowerCase()} cumpriu seu objetivo.`,
 `Avalie clareza, utilidade, organização, originalidade, precisão e acabamento.`,
 `Revise todo o conteúdo antes de apresentar a resposta final.`,
 `Remova qualquer trecho repetido, contraditório ou desconectado do objetivo.`,
 `Confirme que o exemplo corresponde às orientações ensinadas anteriormente.`,
 `Confirme que a linguagem permanece adequada a ${audience} do início ao fim.`,
 `Confirme que nenhuma informação importante foi tratada como verdadeira sem base.`,
 `Não invente pesquisas, números, clientes, depoimentos, resultados ou fontes.`,
 `Quando mencionar uma informação verificável, deixe claro como ela deve ser conferida.`,
 `Não apresente sucesso, vendas, alcance ou rendimento como consequência garantida.`,
 `Não copie textos conhecidos nem reproduza materiais de terceiros.`,
 `Crie uma entrega original baseada exclusivamente no objetivo deste prompt.`,
 `Inclua uma revisão final que melhore ritmo, gramática, precisão e legibilidade.`,
 `Faça uma última leitura pensando como alguém que nunca estudou ${subject}.`,
 `Corrija qualquer passagem que exija conhecimento não explicado anteriormente.`,
 `Garanta que a pessoa saiba exatamente o que fazer depois de terminar a leitura.`,
 `Finalize a parte principal com uma síntese curta do que foi construído.`,
 `Apresente uma lista prática com os elementos que precisam estar presentes na versão final.`,
 `Apresente uma lista separada com os elementos que devem ser evitados.`,
 `Inclua um plano de aplicação para o primeiro dia.`,
 `Inclua uma continuação possível para os sete dias seguintes.`,
 `Inclua uma orientação para melhorar o material depois de receber opiniões reais.`,
 `Mostre como salvar, organizar ou exportar a entrega criada no ${name}.`,
 `Mostre como manter uma cópia editável antes de publicar ou enviar a versão final.`,
 `Entregue o conteúdo completo sem interromper a resposta para fazer perguntas.`,
 `Não use campos vazios, colchetes, formulários ou instruções para o usuário preencher depois.`,
 `Não transforme a resposta em uma lista de perguntas ou em um diagnóstico.`,
 `Não numere estas instruções nem explique que está seguindo um prompt.`,
 `Comece diretamente pela criação de ${title.toLowerCase()} e termine somente quando a entrega estiver completa.`
 ].join('\n');
}
function distinctPrompt(tool,title,audience,skill,scenario,i){
 const toolIndex=tools.indexOf(tool),id=toolIndex*100+i+1,kind=i%10;
 const openings=['Desenvolva uma solução estratégica de','Crie uma entrega editorial completa de','Planeje uma produção visual aplicável de','Estruture um sistema operacional de','Transforme este objetivo em uma campanha de','Construa um material didático avançado de','Desenhe um processo comercial claro de','Prepare uma análise crítica e verificável de','Produza uma referência prática de','Modele uma execução autoral de'];
 const directions=['diagnóstico de contexto e decisão','arquitetura de conteúdo e narrativa','composição, hierarquia e apresentação','entrada, processo, controle e saída','mensagem, prova real e distribuição','explicação progressiva e exercício','oferta, objeção, acompanhamento e limite','evidências, comparação e conclusão','modelo, exemplo e adaptação','planejamento, produção, teste e melhoria'];
 const deliveries=['mapa de decisão','documento pronto para uso','direção criativa detalhada','procedimento verificável','campanha com peças conectadas','guia de aplicação','sequência comercial responsável','relatório crítico','kit editável','plano de execução'];
 const checks=['clareza para iniciantes','coerência entre as etapas','adequação ao canal escolhido','viabilidade com os recursos disponíveis','veracidade das promessas','utilidade imediata','consistência comercial','qualidade das evidências','originalidade da entrega','possibilidade de revisão'];
 const variants=['enxuta para testar','intermediária para aplicar','avançada para apresentar profissionalmente'];
 const seed=`${tool.code}-${String(i+1).padStart(3,'0')}-${String(scenario)}${toolIndex}`;
 return [
  `${openings[kind]} “${title}” usando ${tool.name}, para ${audience}.`,
  `Este é o projeto exclusivo ${seed}; trabalhe com foco em ${directions[kind]}.`,
  `A entrega final deve ser um ${deliveries[kind]} que resolva um problema real relacionado a ${skill.toLowerCase()}.`,
  'Não faça um questionário, não devolva campos vazios e não explique como este comando foi construído.',
  'Comece assumindo o objetivo e avance até uma entrega completa, pronta para revisar e aplicar.',
  `Considere o nível, as limitações e o contexto de ${audience} em todas as decisões.`,
  'Use somente informações fornecidas; quando faltar algum dado factual, declare a hipótese de forma visível.',
  'Não invente números, pesquisas, fontes, depoimentos, resultados, clientes ou provas de venda.',
  `Defina a transformação observável que “${title}” deve proporcionar sem prometer lucro ou resultado garantido.`,
  'Escolha uma ideia central e mantenha todas as partes conectadas a ela.',
  `Organize a primeira parte como ${directions[kind]}, com um começo que situe o problema sem enrolação.`,
  'Mostre o que deve existir antes da execução e por que cada item é necessário.',
  'Liste os materiais, referências e limites que influenciam a qualidade final.',
  `Explique como ${tool.name} deve ser usado nesta tarefa sem atribuir recursos que a ferramenta não possui.`,
  `Construa uma sequência de ações específica para ${skill.toLowerCase()}, evitando conselhos genéricos.`,
  'Faça cada ação gerar uma saída verificável que alimente a ação seguinte.',
  'Inclua uma decisão principal, duas alternativas possíveis e o critério para escolher entre elas.',
  'Apresente os riscos mais prováveis e a forma prática de reduzi-los.',
  `Escreva uma versão completa adequada a ${audience}, com linguagem clara e vocabulário compatível.`,
  `Inclua um exemplo preenchido no cenário ${scenario}.${toolIndex+1}, mostrando decisões e resultado.`,
  'Explique por que o exemplo funciona e quais aspectos não devem ser copiados cegamente.',
  'Depois do exemplo, entregue uma versão adaptável sem usar lacunas vazias ou perguntas soltas.',
  `Crie também uma alternativa com abordagem diferente, preservando o objetivo de ${title.toLowerCase()}.`,
  'Compare as duas abordagens por esforço, clareza, risco, tempo e facilidade de revisão.',
  `Prepare as três escalas: ${variants.join(', ')}.`,
  'Diga o que muda de forma concreta entre as escalas e quando usar cada uma.',
  'Se houver texto, organize títulos que revelem o conteúdo em vez de rótulos vagos.',
  'Se houver visual, descreva hierarquia, contraste, enquadramento, ritmo e legibilidade.',
  'Se houver vídeo, descreva abertura, acontecimento principal, quadro final e espaço para texto de edição.',
  'Se houver pesquisa, separe observação, fonte verificável, interpretação e conclusão.',
  'Se houver comunicação comercial, mostre valor, limites, público adequado e próximo passo verdadeiro.',
  'Não use urgência falsa, escassez inventada, promessas de riqueza ou depoimentos não fornecidos.',
  `Revise a entrega usando o critério “${checks[kind]}”.`,
  'Elimine frases que poderiam servir para qualquer nicho ou qualquer ferramenta.',
  `Garanta que cada orientação seja útil especificamente para ${skill.toLowerCase()} no ${tool.name}.`,
  'Verifique se o resultado pode ser entendido sem conhecer as etapas internas do processo.',
  'Verifique se exemplos, decisões e orientações não entram em contradição.',
  'Verifique direitos de uso de imagens, marcas, referências e dados antes de recomendar publicação.',
  'Ajuste gramática, ritmo, precisão e formato antes de apresentar a versão final.',
  'Entregue primeiro uma síntese executiva curta e depois o material completo.',
  `Prepare uma checklist própria para ${title.toLowerCase()}, incluindo revisão, teste e próximo passo.`,
  'Inclua uma etapa de preparação para evitar começar sem objetivo, referência ou condição de uso.',
  'Inclua uma etapa de produção que transforme a ideia central em uma primeira versão concreta.',
  'Inclua uma etapa de revisão independente da produção, com foco em incoerências e lacunas.',
  'Inclua uma etapa de teste com pessoa, canal ou situação compatível com o público definido.',
  'Inclua uma etapa de melhoria baseada em evidência observada, não em opinião genérica.',
  'Diga o que deve ser salvo como versão editável e o que deve ser exportado como versão final.',
  'Mostre como nomear arquivos, blocos ou versões para evitar confusão em revisões posteriores.',
  'Se a entrega depender de dados externos, indique a fonte que deve ser verificada antes da publicação.',
  'Se a entrega envolver público, diferencie uma suposição inicial de uma validação real.',
  'Se a entrega tiver preço, prazo ou escopo, deixe essas informações transparentes e sem esconder limitações.',
  'Se a entrega for educacional, inclua prática e evidência de aplicação, não apenas teoria.',
  'Se a entrega for comercial, mostre o problema, o mecanismo, o que está incluído e o que não está incluído.',
  'Se a entrega for criativa, preserve originalidade sem imitar obra, pessoa, marca ou estilo protegido.',
  'Se a entrega usar IA, revise informações factuais antes de tratar qualquer afirmação como verdadeira.',
  `Escolha um nome interno claro para o resultado do projeto ${seed}.`,
  'Escreva uma breve justificativa para a ordem escolhida, usando causa e consequência concretas.',
  'Evite repetir a mesma recomendação com sinônimos para aumentar artificialmente o texto.',
  'Evite termos técnicos sem explicação quando houver alternativa em linguagem simples.',
  'Evite listas longas sem prioridade, contexto ou critério de escolha.',
  'Evite recomendações que exijam recursos não mencionados sem oferecer uma alternativa acessível.',
  `Defina como ${audience} perceberá que a primeira versão está pronta para ser testada.`,
  'Defina qual sinal exige voltar uma etapa e corrigir antes de continuar.',
  'Defina qual informação precisa ser registrada para que uma melhoria futura seja possível.',
  'Defina uma forma de comparar a versão inicial com a versão revisada sem manipular o resultado.',
  'Inclua um bloco de observações finais separado do conteúdo principal.',
  'Inclua um plano de aplicação no primeiro dia que caiba em uma ação concreta.',
  'Inclua uma sequência de continuidade para os próximos sete dias, com prioridade e dependência claras.',
  'Inclua uma forma de receber retorno sem pressionar a pessoa por elogios ou compra.',
  'Inclua uma decisão de encerramento: publicar, testar novamente, ajustar ou abandonar com base na evidência.',
  'Revise se o começo e o final respondem ao mesmo objetivo.',
  'Revise se as orientações técnicas combinam com a ferramenta indicada.',
  'Revise se o material continua útil quando lido por alguém que não conhece o projeto.',
  'Revise se todas as escolhas podem ser explicadas sem usar promessas impossíveis.',
  'Apresente a resposta final em blocos bem separados, mas sem repetir o mesmo conteúdo em cada bloco.',
  'Não peça confirmação antes de entregar; faça a melhor versão possível com o contexto disponível.',
  'Inclua uma última conferência de compatibilidade entre formato, ferramenta, público e objetivo.',
  'Inclua uma orientação objetiva sobre o que revisar antes de compartilhar a entrega com outras pessoas.',
  'Inclua uma decisão final de qualidade que deixe claro se o material está pronto ou precisa de ajuste.',
  `Encerre somente quando o projeto ${seed} estiver completo, útil e diferente dos demais prompts.`
 ].join('\n');
}
function card(t,i){return `<button class="ai-directory ${t.tone}" data-ai-open="${i}"><div class="ai-cover"><span>${t.code}</span><i></i><i></i></div><div class="ai-card-copy"><small>${esc(t.plan||`100 PROMPTS · ${t.use}`)}</small><h3>${esc(t.name)}</h3><p>${esc(`Use ${t.name} para ${t.use.toLowerCase()} com tarefas organizadas por objetivo.`)}</p><b>Abrir diretório →</b></div></button>`}
function render(){const c=document.querySelector('#content');if(!c)return;const total=tools.length*100;c.innerHTML=`<section class="academy-hero"><div><p class="eyebrow">ACADEMIA DE INTELIGÊNCIAS ARTIFICIAIS</p><h2>Uma entrada para cada <span>inteligência.</span></h2><p>Escolha a ferramenta pelo resultado que você precisa. Cada capa abre um diretório independente com 100 prompts detalhados.</p></div><div class="academy-count"><strong>${total.toLocaleString('pt-BR')}</strong><span>prompts disponíveis</span><small>${tools.length} ferramentas · 100 em cada diretório</small></div></section><div class="academy-heading"><div><p class="eyebrow">ESCOLHA SUA FERRAMENTA</p><h3>Diretórios separados por finalidade</h3></div><label class="academy-search">⌕ <input id="ai-search" placeholder="Buscar uma IA ou finalidade"></label></div><div class="ai-directory-grid" id="ai-grid">${tools.map(card).join('')}</div>`;bind();document.querySelector('#page-title').textContent='Academia de IAs';document.querySelector('#breadcrumb').textContent=`ONTOP • ${total.toLocaleString('pt-BR')} PROMPTS`}
function openTool(index){const t=tools[index],c=document.querySelector('#content');c.innerHTML=`<button class="academy-back" id="ai-back">← Voltar para as ${tools.length} IAs</button><section class="ai-detail-head ${t.tone}"><div class="ai-detail-logo">${t.code}</div><div><p class="eyebrow">DIRETÓRIO · 100 PROMPTS</p><h2>${esc(t.name)}</h2><p>${esc(t.use)}</p>${t.plan?`<p><strong>${esc(t.plan)}</strong> · condições podem mudar; confirme no site oficial.</p>`:''}<a href="${t.url}" target="_blank" rel="noopener noreferrer">Abrir site oficial ↗</a></div></section><div class="prompt-toolbar"><div><h3>Escolha uma tarefa</h3><p>Abra, ajuste os detalhes do projeto e copie.</p></div><label>⌕ <input id="prompt-search" placeholder="Buscar nos 100 prompts"></label></div><div id="prompt-grid" class="prompt-grid">${Array.from({length:100},(_,i)=>promptCard(t,index,i)).join('')}</div>`;document.querySelector('#ai-back').onclick=render;bindPromptSearch(t,index);bindCopies(t);window.scrollTo({top:0,behavior:'smooth'})}
function promptCard(t,k,i){return `<details class="prompt-card" data-title="${esc(promptTitle(t,i).toLowerCase())}"><summary><i>${String(i+1).padStart(3,'0')}</i><span><strong>${esc(promptTitle(t,i))}</strong><small>${esc(t.use)}</small></span><b>+</b></summary><div><pre>${esc(prompt(t,i))}</pre><button class="secondary" data-copy="${k}:${i}">Copiar prompt</button></div></details>`}
function bind(){document.querySelectorAll('[data-ai-open]').forEach(b=>b.onclick=()=>openTool(+b.dataset.aiOpen));const s=document.querySelector('#ai-search');if(s)s.oninput=()=>{const q=s.value.toLowerCase();document.querySelector('#ai-grid').innerHTML=tools.map((t,i)=>({t,i})).filter(x=>`${x.t.name} ${x.t.use}`.toLowerCase().includes(q)).map(x=>card(x.t,x.i)).join('');document.querySelectorAll('[data-ai-open]').forEach(b=>b.onclick=()=>openTool(+b.dataset.aiOpen))}}
function bindPromptSearch(t,k){const s=document.querySelector('#prompt-search');s.oninput=()=>{const q=s.value.toLowerCase();document.querySelectorAll('.prompt-card').forEach(x=>x.hidden=!x.dataset.title.includes(q))}}
function bindCopies(t){document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{const [,i]=b.dataset.copy.split(':').map(Number);try{await navigator.clipboard.writeText(prompt(t,i));b.textContent='Copiado ✓'}catch{b.textContent='Selecione e copie o texto'}})}
function inject(){const nav=document.querySelector('#nav');if(!nav||document.querySelector('#academy-link'))return;const b=document.createElement('button');b.id='academy-link';b.className='nav-btn academy-main-link';b.innerHTML='<span>✦</span> Academia de IAs';b.onclick=render;nav.prepend(b)}
new MutationObserver(inject).observe(document.body,{subtree:true,childList:true});inject();window.OnTopAcademy={render};
