const catalogEsc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
let catalogProducts=[];
async function loadCatalog(){try{const response=await fetch('/api/catalog',{cache:'no-store'});const body=await response.json();catalogProducts=(body.products||[]).filter(product=>String(product.id).toLowerCase()==='plus'||String(product.tier).toLowerCase()==='plus')}catch{catalogProducts=[]}}
function priceBlock(product){if(!product.price&&!product.salePrice)return '';return `<div class="product-price">${product.salePrice&&product.price?`<del>${catalogEsc(product.price)}</del>`:''}<strong>${catalogEsc(product.salePrice||product.price)}</strong><small>pagamento único</small></div>`}
function benefitsBlock(product,limit){const items=(product.benefits||[]).slice(0,limit);return items.length?`<ul class="product-benefits">${items.map(item=>`<li>${catalogEsc(item)}</li>`).join('')}</ul>`:''}
function productCard(product){return `<article class="product-card ${product.featured?'featured':''}">${product.cover?`<img class="product-cover" src="${catalogEsc(product.cover)}" alt="Capa de ${catalogEsc(product.title)}" loading="lazy">`:'<div class="product-cover placeholder">O</div>'}<div class="product-card-body">${product.badge?`<span class="badge gold">${catalogEsc(product.badge)}</span>`:product.featured?'<span class="badge gold">DESTAQUE</span>':''}${product.tier?`<small class="product-tier">PLANO ${catalogEsc(product.tier)}</small>`:''}<h3>${catalogEsc(product.title)}</h3><p>${catalogEsc(product.shortDescription||product.description||'Conheça os detalhes deste produto.')}</p>${priceBlock(product)}${benefitsBlock(product,4)}<div class="product-actions"><button class="secondary" data-product-details="${catalogEsc(product.id)}">Ver detalhes</button><a class="primary product-link" href="${catalogEsc(product.url)}" target="_blank" rel="noopener noreferrer sponsored">Acessar produto</a></div></div></article>`}
function renderCatalog(){const content=document.querySelector('#content');if(!content)return;document.querySelectorAll('.nav-btn').forEach(button=>button.classList.remove('active'));document.querySelector('#catalog-link')?.classList.add('active');document.querySelector('#page-title').textContent='Produtos e links';document.querySelector('#breadcrumb').textContent='ONTOP • VITRINE';content.innerHTML=`<section class="hero"><p class="eyebrow">VITRINE ATUALIZADA</p><h3>Produtos e recursos <span class="gold">OnTop</span></h3><p>Capas, descrições, preços e links administrados em tempo real pelo painel OnTop.</p></section><section class="catalog-grid">${catalogProducts.length?catalogProducts.map(productCard).join(''):'<div class="card full catalog-empty"><h3>A vitrine está sendo preparada</h3><p>Todo o restante da Central continua disponível normalmente.</p></div>'}</section>`;content.querySelectorAll('[data-product-details]').forEach(button=>button.onclick=()=>showProductDetails(catalogProducts.find(product=>product.id===button.dataset.productDetails)))}
function showProductDetails(product){if(!product)return;const modal=document.createElement('div');modal.className='modal';const gallery=(product.images||[]).map(src=>`<img src="${catalogEsc(src)}" alt="Foto de ${catalogEsc(product.title)}" loading="lazy">`).join('');modal.innerHTML=`<div class="modal-box product-modal"><button class="secondary close-product" type="button">Fechar</button>${product.cover?`<img class="product-modal-cover" src="${catalogEsc(product.cover)}" alt="Capa de ${catalogEsc(product.title)}">`:''}<p class="eyebrow">${product.tier?`PLANO ${catalogEsc(product.tier)}`:'PRODUTO ONTOP'}</p><h2>${catalogEsc(product.title)}</h2><p class="product-description">${catalogEsc(product.description||product.shortDescription)}</p>${priceBlock(product)}${benefitsBlock(product,20)}${gallery?`<div class="product-gallery">${gallery}</div>`:''}<a class="primary product-link large" href="${catalogEsc(product.url)}" target="_blank" rel="noopener noreferrer sponsored">Acessar produto</a></div>`;document.body.append(modal);modal.onclick=event=>{if(event.target===modal||event.target.closest('.close-product'))modal.remove()}}
let catalogInjecting=false;
async function injectCatalog(){
 const nav=document.querySelector('#nav');
 if(!nav||document.querySelector('#catalog-link')||catalogInjecting)return;
 catalogInjecting=true;
 const label=document.createElement('p');label.id='catalog-label';label.textContent='PRODUTOS';
 const button=document.createElement('button');button.id='catalog-link';button.className='nav-btn';button.innerHTML='<span>◆</span> Produtos e links';
 button.onclick=async()=>{await loadCatalog();renderCatalog()};
 nav.prepend(button);nav.prepend(label);
 await loadCatalog();
 catalogInjecting=false;
}
window.OnTopCatalog={load:loadCatalog,render:async()=>{await loadCatalog();renderCatalog()}};
