const e=value=>String(value??'').replace(/[&<>"']/g,item=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[item]));

export const directories=[
{id:'start',icon:'◎',title:'Comece por aqui',description:'Entenda a plataforma, escolha um caminho e conclua sua primeira ação com clareza.',modules:['Entenda sua situação','Escolha uma direção','Execute com responsabilidade'],topics:['O que é a Central OnTop','O que a plataforma entrega de verdade','Como usar os diretórios sem pesquisar','Diferença entre aprender e aplicar','Como definir seu ponto de partida','Tempo disponível durante a semana','Conhecimentos que você já possui','Recursos gratuitos para começar','Limites reais de orçamento','Expectativas realistas de resultado','Os três caminhos da OnTop','Quando começar oferecendo serviços','Quando criar um produto digital','Quando priorizar organização financeira','Como escolher apenas uma prioridade','Como reconhecer uma necessidade real','O que fazer quando você não tem experiência','Como montar sua rotina inicial','Primeira meta pequena e verificável','Como acompanhar seu progresso','A primeira tarefa de 30 minutos','Seu primeiro material demonstrativo','Como pedir opinião sem vender','Organização de pastas e arquivos','Como documentar o aprendizado','Quando mudar sua estratégia','Como evitar comparações enganosas','Como registrar erros e melhorias','Checklist da primeira semana','Próximo passo depois do início'],outcome:'uma direção clara e uma primeira tarefa concluída',example:'Escolha criação de conteúdo para comércios locais, reserve 40 minutos por dia e produza um exemplo simples para uma loja fictícia.',mistake:'querer aprender todas as ferramentas antes de concluir uma entrega pequena'},
{id:'first',icon:'↗',title:'Primeiros passos',description:'Saia da teoria com preparação, organização, validação e primeiras entregas.',modules:['Preparação inicial','Primeira oportunidade','Primeira entrega'],topics:['Organize sua rotina de trabalho','Crie uma lista de habilidades','Escolha um público próximo','Entenda problemas cotidianos','Defina um objetivo de sete dias','Prepare um espaço de produção','Configure ferramentas essenciais','Crie um e-mail profissional','Organize arquivos por projeto','Estabeleça um limite de gastos','Identifique uma demanda observável','Compare três tipos de serviço','Converse com pessoas do público','Anote dúvidas e objeções reais','Escolha um problema específico','Defina uma solução pequena','Escreva sua proposta inicial','Monte um exemplo demonstrativo','Mostre a entrega antes de cobrar','Colete comentários úteis','Ajuste sua proposta inicial','Defina prazo e quantidade de revisões','Organize o recebimento de materiais','Registre os combinados por escrito','Entregue uma amostra completa','Peça autorização para usar no portfólio','Acompanhe a satisfação do cliente','Registre tempo e custos','Liste melhorias para a próxima entrega','Planeje sua segunda oportunidade'],outcome:'uma primeira entrega demonstrativa pronta para apresentar',example:'Ofereça três posts demonstrativos para uma cafeteria, explique prazo de dois dias e apresente os arquivos em uma pasta organizada.',mistake:'cobrar ou prometer resultados antes de demonstrar claramente o que será entregue'},
{id:'income',icon:'◈',title:'Formas de gerar renda',description:'Conheça possibilidades reais de trabalho digital, requisitos, riscos e formas de começar.',modules:['Serviços acessíveis','Produtos digitais','Estratégia responsável'],topics:['Edição de vídeos curtos','Criação de artes para redes sociais','Produção de legendas e textos','Organização de perfis comerciais','Criação de páginas simples','Apoio administrativo remoto','Organização de apresentações','Revisão de materiais digitais','Atendimento para pequenos negócios','Configuração básica de catálogos','E-books educativos','Planilhas de organização','Pacotes de modelos editáveis','Guias práticos por nicho','Roteiros para criadores','Calendários de conteúdo','Materiais para negócios locais','Checklists especializados','Aulas e materiais próprios','Combinação de serviço e produto','Como escolher uma atividade viável','Quanto tempo cada caminho exige','Custos básicos para começar','Habilidades necessárias por atividade','Como produzir uma amostra','Como encontrar os primeiros interessados','Como calcular preço e margem','Como evitar expectativas irreais','Como melhorar após cada entrega','Quando ampliar sua oferta'],outcome:'uma atividade compatível com suas habilidades, tempo e recursos',example:'Um iniciante com celular pode oferecer edição de três vídeos curtos para pequenos negócios, desde que demonstre qualidade e combine o escopo.',mistake:'confundir faturamento possível com faturamento garantido'},
{id:'ebooks',icon:'▤',title:'Criação de e-books',description:'Aprenda a planejar, escrever, revisar, diagramar, publicar e divulgar materiais úteis.',modules:['Planejamento e estrutura','Produção do conteúdo','Publicação e qualidade'],topics:['Escolha do tema do e-book','Identificação do público ideal','Problema específico que será resolvido','Promessa realista do material','Levantamento de referências confiáveis','Análise de materiais semelhantes','Definição do formato adequado','Planejamento do sumário','Organização dos capítulos','Preparação do cronograma','Escrita da introdução','Explicação dos fundamentos','Capítulos com passo a passo','Exemplos totalmente preenchidos','Exercícios para o leitor','Checklists de aplicação','Perguntas frequentes','Conclusão e próximos passos','Uso responsável de IA na escrita','Revisão de fatos e referências','Criação de capa profissional','Escolha de fontes e cores','Diagramação para celular','Inserção de imagens autorizadas','Exportação e conferência do PDF','Teste em diferentes dispositivos','Criação de descrição verdadeira','Cadastro do material na Kiwify','Divulgação sem promessas falsas','Checklist final antes da venda'],outcome:'um e-book organizado, revisado e pronto para leitura',example:'Monte um guia de 25 páginas sobre organização de atendimento, com cinco capítulos, dois exemplos preenchidos e uma checklist final.',mistake:'vender um PDF vazio, copiar conteúdo de terceiros ou anunciar páginas e bônus inexistentes'},
{id:'videos',icon:'▶',title:'Criação de vídeos',description:'Domine planejamento, gravação, edição, narrativa e divulgação de vídeos curtos.',modules:['Estratégia e roteiro','Produção e edição','Publicação e melhoria'],topics:['Objetivo principal do vídeo','Público que você deseja alcançar','Problema apresentado nos primeiros segundos','Tipos de gancho para abertura','Estrutura simples de roteiro','Como escrever uma narração clara','Escolha do formato vertical','Definição da duração adequada','Planejamento de cenas','Materiais e imagens necessários','Iluminação com recursos simples','Captação de áudio sem ruídos','Enquadramento para celular','Gravação de demonstrações reais','Uso de vídeos autorizados','Organização dos cortes','Sincronização entre fala e imagem','Legendas totalmente visíveis','Música e direitos de uso','Ritmo e transições equilibradas','Título que apresenta valor','Legenda para a publicação','Chamada para ação objetiva','Escolha de capa clara','Publicação no Instagram','Publicação no TikTok','Acompanhamento da retenção','Leitura de comentários','Correção de erros recorrentes','Criação de uma série de vídeos'],outcome:'um vídeo curto compreensível, bem editado e pronto para publicação',example:'Abra com uma dúvida real, demonstre três passos em 35 segundos, coloque legendas legíveis e finalize convidando o público a conhecer o material.',mistake:'usar imagens sem autorização, cortar letras ou mostrar cenas que não correspondem à narração'},
{id:'sites',icon:'⌘',title:'Criação de sites',description:'Descubra como planejar, criar, testar, publicar e apresentar sites profissionais.',modules:['Fundamentos do projeto','Construção e publicação','Entrega profissional'],topics:['Qual problema o site resolve','Definição do público do site','Tipos de site mais procurados','Estrutura básica de uma página','Planejamento das seções','Identidade visual do projeto','Textos claros e objetivos','Escolha de imagens autorizadas','Navegação intuitiva no celular','Chamadas para ação úteis','Introdução ao HTML e CSS','Ferramentas de criação assistida','Organização dos arquivos','Uso inicial do GitHub','Criação de um repositório','Preparação para publicação','Importação do projeto na Vercel','Configuração de domínio gratuito','Teste dos links e botões','Verificação de desempenho','Como apresentar uma demonstração','Definição de escopo e prazo','Preço baseado em tempo e custos','Proposta comercial por escrito','Recebimento de informações do cliente','Revisões e aprovação','Checklist de entrega','Orientações de manutenção','Privacidade e dados pessoais','Construção de portfólio próprio'],outcome:'um projeto de site navegável, publicado e documentado',example:'Crie uma página para uma barbearia com apresentação, serviços, localização e botão de contato; teste tudo no celular antes de mostrar.',mistake:'publicar dados pessoais, deixar links quebrados ou prometer funções ainda não implementadas'},
{id:'products',icon:'▦',title:'Produtos digitais',description:'Escolha uma ideia, valide, produza os arquivos e configure uma entrega confiável.',modules:['Escolha e validação','Montagem da entrega','Venda e suporte'],topics:['O que caracteriza um produto digital','Identificação de problemas específicos','Ideias para públicos locais','Ideias para profissionais autônomos','Ideias para criadores de conteúdo','Comparação entre e-book e planilha','Avaliação de custo e esforço','Conversa com possíveis compradores','Teste com uma amostra pequena','Definição da entrega mínima','Organização dos materiais','Criação de arquivos editáveis','Produção de exemplos preenchidos','Elaboração de instruções claras','Separação por módulos e pastas','Criação de bônus realmente úteis','Definição de planos diferentes','Conferência do que foi prometido','Revisão por outra pessoa','Teste de download e abertura','Cadastro do produto na Kiwify','Descrição fiel ao conteúdo','Definição de preço responsável','Configuração da área de membros','Entrega imediata e orientações','Página de vendas transparente','Comunicação depois da compra','Atendimento de dúvidas','Correção de materiais defeituosos','Atualizações e melhorias contínuas'],outcome:'um produto digital verdadeiro, organizado e pronto para entrega',example:'Crie um kit com cinco modelos editáveis, um manual em PDF e um exemplo preenchido; confira cada arquivo antes de cadastrar a oferta.',mistake:'listar centenas de materiais sem verificar se cada item realmente existe e funciona'},
{id:'ai',icon:'✺',title:'Inteligências artificiais',description:'Entenda quando usar cada IA, como escrever instruções e como revisar os resultados.',modules:['Fundamentos e segurança','Ferramentas por finalidade','Aplicação responsável'],topics:['O que uma IA consegue fazer','Limites das respostas automáticas','Diferença entre plano grátis e pago','Como escrever um pedido claro','Contexto necessário para bons resultados','Como especificar o público','Como pedir exemplos concretos','Como solicitar revisão','Cuidados com dados pessoais','Verificação humana obrigatória','ChatGPT para escrita e planejamento','Claude para documentos extensos','Gemini para organização e estudo','Perplexity para fontes verificáveis','Canva para materiais visuais','CapCut para edição de vídeos','Runway para criação visual','ElevenLabs para narrações','Gamma para apresentações','Midjourney para imagens','Fluxo de criação de um e-book','Fluxo para vídeo publicitário','Fluxo para proposta comercial','Fluxo para calendário de conteúdo','Como comparar duas respostas','Como corrigir informações falsas','Como adaptar modelos ao seu negócio','Direitos autorais em conteúdos gerados por IA','Como controlar custos e limites','Como acessar os 1200 prompts OnTop'],outcome:'um fluxo claro de uso de IA com revisão e aplicação prática',example:'Escreva um primeiro rascunho, peça revisão estruturada, confirme fatos em fontes confiáveis e personalize o material antes de entregar.',mistake:'copiar respostas automáticas sem conferir erros, limitações, direitos autorais e contexto'},
{id:'sales',icon:'↗',title:'Divulgação e vendas',description:'Aprenda a apresentar uma oferta, demonstrar valor e conversar com clientes com ética.',modules:['Posicionamento','Conteúdo e relacionamento','Proposta e pós-venda'],topics:['Identifique o público correto','Explique um problema real','Descreva a solução claramente','Defina o que está incluído','Mostre o que não está incluído','Escolha um canal de divulgação','Prepare um perfil profissional','Crie uma biografia objetiva','Organize um link de apresentação','Defina um calendário simples','Posts educativos para Instagram','Vídeos curtos para TikTok','Stories com demonstração','Conteúdo de bastidores','Mensagens iniciais no WhatsApp','Como apresentar exemplos reais','Como responder dúvidas','Como lidar com objeções','Como evitar insistência excessiva','Como registrar contatos interessados','Estrutura de proposta comercial','Explicação transparente de preço','Prazos e revisões combinados','Formalização do pedido','Orientações após a compra','Acompanhamento da entrega','Solicitação de avaliação verdadeira','Organização de indicações','Melhoria da comunicação','Métricas que realmente importam'],outcome:'uma comunicação clara e uma oferta honesta para interessados reais',example:'Mostre duas páginas reais do e-book, explique o conteúdo incluído, informe o preço e deixe claro que resultados dependem de aplicação.',mistake:'inventar depoimentos, exagerar resultados ou enviar mensagens sem autorização'},
{id:'finance',icon:'◒',title:'Organização financeira',description:'Aprenda a registrar valores, calcular custos e tomar decisões com responsabilidade.',modules:['Controle básico','Preço e planejamento','Decisões responsáveis'],topics:['Diferença entre faturamento e lucro','Separação entre pessoal e negócio','Registro de entradas recebidas','Registro de despesas realizadas','Classificação de gastos','Custos fixos e variáveis','Taxas de plataformas','Tempo investido em cada trabalho','Noção inicial de margem','Fechamento semanal simples','Como calcular o custo de uma entrega','Como estimar preço por hora','Como incluir revisões e suporte','Como considerar taxas e impostos','Como comparar cenários','Como definir uma meta possível','Como organizar reserva financeira','Como evitar gastos impulsivos','Como acompanhar pagamentos','Como identificar desperdícios','Noções de orçamento mensal','Riscos de promessas de retorno','Cuidado com empréstimos caros','Sinais de fraudes financeiras','Por que patrimônio leva tempo','Importância de diversificar aprendizado','Quando buscar orientação profissional','Como revisar números antes de decidir','Checklist financeiro mensal','Construção de hábitos consistentes'],outcome:'um controle básico de receitas, custos e decisões financeiras',example:'Registre uma venda de R$ 100, desconte R$ 12 de taxas e R$ 18 de custos e avalie o tempo investido antes de concluir se o trabalho valeu a pena.',mistake:'confundir dinheiro recebido com lucro ou acreditar em investimentos sem risco'},
{id:'journey',icon:'◷',title:'Plano guiado de 90 dias',description:'Organize os primeiros três meses em etapas, metas e entregas verificáveis.',modules:['Dias 1 a 30: fundamentos','Dias 31 a 60: validação','Dias 61 a 90: melhoria'],topics:['Semana 1: diagnóstico inicial','Semana 1: organização de rotina','Semana 1: escolha de habilidades','Semana 2: identificação do público','Semana 2: lista de problemas','Semana 2: conversas iniciais','Semana 3: escolha de uma oferta','Semana 3: criação de demonstração','Semana 4: revisão da proposta','Semana 4: primeira apresentação','Semana 5: organização de contatos','Semana 5: abordagem responsável','Semana 5: coleta de objeções','Semana 6: melhoria da oferta','Semana 6: definição de preço','Semana 6: criação de conteúdo útil','Semana 7: execução de teste','Semana 7: registro de resultados','Semana 8: revisão da entrega','Semana 8: planejamento do próximo ciclo','Semana 9: melhoria de processos','Semana 9: padronização de materiais','Semana 10: organização financeira','Semana 10: acompanhamento de clientes','Semana 11: produção de novos exemplos','Semana 11: revisão de conteúdo','Semana 12: avaliação de indicadores','Semana 12: correção de gargalos','Semana 13: consolidação do aprendizado','Dia 90: balanço e próximos passos'],outcome:'um cronograma de três meses com objetivos e entregas concretas',example:'Nas primeiras quatro semanas, escolha um público, converse com cinco pessoas, produza uma amostra e apresente uma oferta sem prometer renda.',mistake:'repetir tarefas genéricas durante 90 dias sem registrar um resultado concreto'},
{id:'templates',icon:'▧',title:'Modelos prontos',description:'Acesse estruturas práticas de mensagens, propostas, roteiros, checklists e documentos.',modules:['Comunicação pronta','Entrega e organização','Revisão e acompanhamento'],topics:['Primeira mensagem de apresentação','Mensagem de retorno educada','Perguntas para entender um cliente','Convite para conhecer uma amostra','Resposta para quem pede preço','Mensagem para explicar prazo','Confirmação de recebimento','Pedido de materiais necessários','Atualização durante o trabalho','Agradecimento após a entrega','Proposta comercial em formato editável','Modelo de escopo do serviço','Checklist de briefing','Modelo de cronograma','Estrutura de e-book','Modelo de roteiro para vídeo','Sequência para carrossel','Descrição de produto digital','Página de apresentação','Organização de pastas','Checklist antes de publicar','Checklist antes de vender','Checklist de revisão de PDF','Checklist de teste de links','Modelo de registro financeiro','Modelo de acompanhamento de clientes','Perguntas para avaliação verdadeira','Relatório simples de resultados','Plano de melhorias','Mensagem de suporte ao comprador'],outcome:'modelos copiáveis e adaptáveis a situações reais',example:'Modelo: Olá! Preparei uma demonstração relacionada a [PROBLEMA]. Posso enviar uma explicação curta sobre o que está incluído e o prazo?',mistake:'usar textos copiados sem personalizar o contexto, os limites e a necessidade do cliente'},
{id:'safety',icon:'⚑',title:'Erros, riscos e golpes',description:'Reconheça sinais de fraude e construa ofertas transparentes que realmente entregam valor.',modules:['Sinais de alerta','Transparência comercial','Proteção do cliente'],topics:['Promessa de renda garantida','Falso prazo de enriquecimento','Depoimento inventado','Print de faturamento manipulado','Contagem falsa de materiais','Arquivo vazio ou incompleto','Curso sem conteúdo anunciado','Bônus inexistente','Pressão exagerada para comprar','Falsa prova de autoridade','Como descrever uma entrega real','Como mostrar exemplos verdadeiros','Como informar limitações','Como explicar esforço necessário','Como conferir links e arquivos','Como respeitar direitos autorais','Como proteger dados pessoais','Como registrar condições da oferta','Como responder dúvidas com honestidade','Como corrigir erros rapidamente','Como identificar cobrança suspeita','Como avaliar uma ferramenta desconhecida','Como evitar compartilhamento de senhas','Como proteger códigos individuais','Como validar páginas oficiais','Como analisar propostas irreais','Como documentar um problema','Como buscar orientação adequada','Checklist de confiança','Compromisso OnTop com transparência'],outcome:'uma lista prática de cuidados antes de comprar, vender ou publicar',example:'Antes de anunciar “100 modelos”, abra os arquivos, conte os modelos, teste o download e mostre exemplos reais do que será entregue.',mistake:'achar que um aviso comercial elimina obrigações legais ou justifica entregar menos do que foi prometido'},
{id:'faq',icon:'?',title:'Dúvidas frequentes',description:'Encontre respostas diretas e organizadas para as dúvidas mais comuns de quem está começando.',modules:['Sobre o começo','Sobre ferramentas e vendas','Sobre resultados e segurança'],topics:['Preciso ter experiência para começar?','Preciso investir dinheiro imediatamente?','Posso começar usando apenas o celular?','Quantas horas preciso separar?','Qual caminho devo escolher primeiro?','Como descubro o que oferecer?','Onde encontro meus primeiros interessados?','Como monto um exemplo sem cliente?','Posso usar inteligência artificial?','Como sei se um material está pronto?','Como criar um e-book útil?','Como produzir um vídeo curto?','Como publicar um site simples?','Como cadastrar um produto digital?','Como definir um preço inicial?','Como explicar minha oferta?','Como receber informações do cliente?','Como organizar revisões?','Como divulgar sem incomodar?','Como acompanhar minhas tarefas?','Existe garantia de faturamento?','Quanto tempo leva para aprender?','O que fazer quando não tenho resultado?','Como evitar promessas falsas?','Como conferir fontes e informações?','Posso copiar materiais de outras pessoas?','Como cuidar dos meus dados?','Como proteger o código de acesso?','Quando devo pedir ajuda especializada?','Qual é meu próximo passo agora?'],outcome:'respostas claras para as principais dúvidas da sua jornada',example:'Não existe garantia de faturamento. Resultados dependem do mercado, das suas habilidades, da qualidade da oferta e da execução consistente.',mistake:'esperar uma resposta universal quando a decisão depende de contexto, riscos e recursos disponíveis'}
];

const progressKey='ontop-guide-progress-v1';
const evidenceKey='ontop-guide-evidence-v1';
const readProgress=()=>{try{return JSON.parse(localStorage.getItem(progressKey)||'{}')}catch{return {}}};
const writeProgress=value=>localStorage.setItem(progressKey,JSON.stringify(value));
const readEvidence=()=>{try{return JSON.parse(localStorage.getItem(evidenceKey)||'{}')}catch{return {}}};
const writeEvidence=value=>localStorage.setItem(evidenceKey,JSON.stringify(value));
const levels=['Entender a situação e registrar o ponto de partida','Preparar uma solução pequena e demonstrável','Aplicar, revisar e documentar os resultados'];

const methods={
 start:{method:'diagnóstico pessoal, escolha de prioridade e registro de evidências',tool:'uma folha de decisão com situação, recurso, limite e próxima ação',measure:'uma decisão escrita que possa ser executada nesta semana'},
 first:{method:'prática deliberada, amostra demonstrativa e conversa com pessoas reais',tool:'briefing, pasta de projeto, cronograma e checklist de entrega',measure:'uma amostra compreensível e revisada por outra pessoa'},
 income:{method:'comparação entre demanda, habilidade, custo e acesso ao público',tool:'matriz com atividade, requisito, amostra, prazo, custo e risco',measure:'uma atividade escolhida por evidência, e não apenas por expectativa'},
 ebooks:{method:'pesquisa, arquitetura editorial, escrita modular e revisão em PDF',tool:'sumário, fontes, capítulos, exemplos preenchidos e checklist de leitura no celular',measure:'um capítulo útil, verificável e pronto para ser testado'},
 videos:{method:'roteiro visual, gravação vertical, edição por intenção e análise de retenção',tool:'roteiro com gancho, cenas, narração, legenda, prova e chamada para ação',measure:'um vídeo legível, coerente com a fala e assistível até o final'},
 sites:{method:'requisitos, estrutura semântica, desenvolvimento responsivo, testes e publicação',tool:'mapa de seções, HTML, CSS, links, repositório, implantação e checklist móvel',measure:'uma página navegável, rápida e sem links ou textos quebrados'},
 products:{method:'pesquisa do problema, produto mínimo útil, testes de arquivo e entrega',tool:'mapa da entrega, arquivos editáveis, exemplo preenchido e instruções de acesso',measure:'um pacote que entrega exatamente o que a oferta descreve'},
 ai:{method:'definição de tarefa, contexto, instrução estruturada e revisão humana',tool:'prompt com papel, contexto, restrições, formato, fontes e critérios de qualidade',measure:'uma resposta verificada, personalizada e adequada ao uso pretendido'},
 sales:{method:'posicionamento, demonstração de valor, conversa autorizada e acompanhamento do funil',tool:'perfil, conteúdo educativo, prova real, proposta e registro de contatos',measure:'visitas, respostas, cliques e decisões registradas sem promessas enganosas'},
 finance:{method:'registro de entradas e saídas, separação de custos e comparação de cenários',tool:'controle financeiro com data, categoria, valor, taxa, custo e saldo',measure:'números conciliados e uma decisão compatível com o orçamento'},
 journey:{method:'execução progressiva em diagnóstico, pesquisa, solução, validação, oferta, divulgação, entrega e melhoria',tool:'registro diário com ação, evidência, aprendizado e próxima decisão',measure:'uma evidência diferente e acumulativa em cada etapa'},
 templates:{method:'modelagem de documentos com campos editáveis, exemplo preenchido e instruções',tool:'modelo copiável com objetivo, campos obrigatórios, limites e checklist de revisão',measure:'um documento que outra pessoa consiga adaptar sem explicação adicional'},
 safety:{method:'verificação de promessa, evidência, direitos, privacidade e risco para o comprador',tool:'checklist de sinais de alerta, origem da informação e ação segura',measure:'uma decisão documentada que reduza exposição a fraude ou informação falsa'},
 faq:{method:'resposta direta, contexto, opções e próximo passo',tool:'quadro com resposta curta, quando se aplica, exceções e ação recomendada',measure:'uma dúvida respondida sem transformar opinião em regra universal'}
};

function sentenceTopic(title){return title.replace(/\?$/,'').replace(/^Como\s+/i,'').replace(/^O que\s+/i,'').trim()}

export function lesson(category,index){
 const title=category.topics[index],phase=Math.floor(index/10),module=category.modules[phase];
 const profile=methods[category.id],subject=sentenceTopic(title),categoryIndex=directories.findIndex(item=>item.id===category.id),globalIndex=categoryIndex*30+index;
 const starts=['Explore','Investigue','Construa','Analise','Mapeie','Experimente','Organize','Compare','Desenvolva','Aplique','Modele','Planeje','Observe','Estruture','Teste','Documente','Prepare','Transforme','Demonstre','Aprimore','Configure','Esboce','Valide','Conecte','Revise','Simule','Componha','Projete','Delimite','Execute'];
 const introModes=['com uma situação real','por meio de uma decisão prática','usando uma demonstração pequena','a partir de uma evidência observável','com foco na aplicação imediata','por uma comparação objetiva','usando um caso específico','com uma entrega verificável','a partir de um problema concreto','com critérios definidos'];
 const directAnswer=`${starts[globalIndex%starts.length]} “${title}” ${introModes[(globalIndex+phase)%introModes.length]}. Nesta aula do diretório ${category.title}, você utilizará ${profile.method} para alcançar ${category.outcome}.`;
 const baseSteps=[
  `${starts[(globalIndex+3)%starts.length]} o ponto de partida de “${title}” e registre o que já existe, o que falta e qual resultado será observado ao final.`,
  `${starts[(globalIndex+7)%starts.length]} ${profile.tool} exclusivamente para “${subject.toLowerCase()}”, preenchendo cada parte com informações ligadas ao cenário escolhido.`,
  `${starts[(globalIndex+11)%starts.length]} uma primeira versão de “${title}” sem dados pessoais ou resultados inventados, mantendo apenas elementos que possam ser conferidos.`,
  `${starts[(globalIndex+17)%starts.length]} a versão produzida para “${title}” com base neste critério particular: ${profile.measure}.`,
  `${starts[(globalIndex+23)%starts.length]} uma melhoria exclusiva em “${subject.toLowerCase()}”, compare antes e depois e explique por que a mudança tornou a entrega mais útil.`
 ];
 const example=`Aplicação de “${title}”: ${category.example} Adapte esse cenário ao objetivo de ${subject.toLowerCase()}, registre a decisão tomada e destaque o efeito observável dessa escolha.`;
 const exercise=`Atividade exclusiva de “${title}”: produza uma versão usando ${profile.tool}, reserve ${30+(globalIndex%4)*10} minutos, faça um teste relacionado a ${subject.toLowerCase()} e identifique uma alteração necessária.`;
 const deliverable=`Resultado esperado para “${title}”: apresente ${profile.tool}, aplicado a ${subject.toLowerCase()}, junto de uma evidência de conclusão, uma limitação encontrada e uma próxima decisão específica.`;
 const warning=`Cuidado particular em “${title}”: evite ${category.mistake}; antes de concluir ${subject.toLowerCase()}, confira a precisão, a compatibilidade e os direitos de uso dos elementos utilizados.`;
 const checklist=[
  `Consigo explicar “${title}” por meio do exemplo específico criado nesta aula`,
  `Preenchi ${profile.tool} com dados diretamente relacionados a “${subject.toLowerCase()}”`,
  `Testei “${title}” usando o critério ${profile.measure} e registrei o resultado`,
  `Salvei a evidência de “${subject.toLowerCase()}” e defini uma melhoria diferente para a próxima execução`
 ];
 const formats=[
  {name:'Oficina aplicada',actions:'Construção guiada',example:'Demonstração da oficina',exercise:'Produção individual',deliverable:'Peça final da oficina',warning:'Ponto de controle',checklist:'Critérios da oficina'},
  {name:'Estudo de caso',actions:'Leitura do caso',example:'Caso analisado',exercise:'Decisão sobre o caso',deliverable:'Solução documentada',warning:'Risco do caso',checklist:'Validação do estudo'},
  {name:'Comparação prática',actions:'Critérios de comparação',example:'Alternativas comparadas',exercise:'Escolha justificada',deliverable:'Matriz concluída',warning:'Erro de comparação',checklist:'Conferência da escolha'},
  {name:'Auditoria orientada',actions:'Itens da auditoria',example:'Falha identificada',exercise:'Correção auditada',deliverable:'Registro da auditoria',warning:'Sinal de alerta',checklist:'Controle da auditoria'},
  {name:'Simulação realista',actions:'Preparação da simulação',example:'Cenário simulado',exercise:'Resposta ao cenário',deliverable:'Resultado da simulação',warning:'Limite da simulação',checklist:'Revisão do cenário'},
  {name:'Projeto em etapas',actions:'Etapas do projeto',example:'Projeto demonstrativo',exercise:'Execução do projeto',deliverable:'Versão do projeto',warning:'Gargalo do projeto',checklist:'Qualidade do projeto'},
  {name:'Desafio verificável',actions:'Regras do desafio',example:'Desafio resolvido',exercise:'Sua tentativa',deliverable:'Evidência do desafio',warning:'Erro a evitar',checklist:'Conclusão do desafio'}
 ];
 const format=formats[globalIndex%formats.length];
 const formatStep=`${starts[(globalIndex+27)%starts.length]} a atividade no formato “${format.name}”: associe uma evidência concreta a “${subject.toLowerCase()}” e registre a conclusão sem usar respostas genéricas.`;
 const stepLayouts=[
  [baseSteps[0],baseSteps[1],baseSteps[2],baseSteps[3],baseSteps[4]],
  [baseSteps[0],baseSteps[2],baseSteps[3],formatStep],
  [baseSteps[1],baseSteps[0],formatStep,baseSteps[2],baseSteps[3],baseSteps[4]],
  [baseSteps[3],baseSteps[0],baseSteps[2],baseSteps[4],formatStep],
  [baseSteps[0],formatStep,baseSteps[2],baseSteps[4]],
  [baseSteps[0],baseSteps[1],baseSteps[2],formatStep,baseSteps[3],baseSteps[4]],
  [formatStep,baseSteps[1],baseSteps[2],baseSteps[3],baseSteps[4]]
 ];
 const steps=stepLayouts[globalIndex%stepLayouts.length];
 return {title,module,phase,introduction:directAnswer,steps,example,exercise,deliverable,warning,checklist,format};
}

function counts(){const done=Object.keys(readProgress()).filter(key=>readProgress()[key]).length;return {done,total:directories.reduce((sum,item)=>sum+item.topics.length,0)}}

function categoryCard(category){const completed=category.topics.filter((_,i)=>readProgress()[`${category.id}-${i}`]).length;return `<button class="guide-directory" data-guide-category="${e(category.id)}"><span class="guide-directory-icon">${e(category.icon)}</span><span class="guide-directory-body"><strong>${e(category.title)}</strong><small>${e(category.description)}</small><span class="guide-directory-meta">30 aulas guiadas · ${completed} concluídas</span></span><span class="guide-directory-arrow">→</span></button>`}

function home(){const {done,total}=counts();return `<section class="guide-hero"><div><p class="eyebrow">PLATAFORMA DE APRENDIZADO · ONTOP PLUS</p><h2>Aprenda com um caminho claro, <span>passo a passo.</span></h2><p>Escolha uma categoria e abra as aulas prontas. Você não precisa pesquisar o que fazer: cada conteúdo explica o objetivo, os passos, um exemplo, o exercício e os cuidados importantes.</p><div class="guide-hero-actions"><button class="primary guide-primary" data-guide-category="start">Começar do zero</button><button class="secondary" data-guide-category="ai">Conhecer as IAs</button></div></div><div class="guide-summary"><strong>${total}</strong><span>aulas e materiais guiados</span><div class="guide-summary-line"><b>14</b><small>áreas práticas</small></div><div class="guide-summary-line"><b>${done}</b><small>aulas concluídas</small></div><div class="guide-summary-line"><b>1.200</b><small>prompts detalhados</small></div></div></section><section class="guide-notice">✦ Siga os diretórios na ordem recomendada ou escolha o assunto que você precisa agora. Todas as aulas já estão organizadas e explicadas.</section><div class="guide-heading"><div><p class="eyebrow">SEU MAPA COMPLETO</p><h3>14 caminhos para aprender e aplicar</h3></div><span class="guide-badge">${done}/${total} concluídas</span></div><div class="guide-directory-grid">${directories.map(categoryCard).join('')}</div><section class="guide-ethics"><strong>Compromisso OnTop</strong><p>A plataforma é educacional. Não existe garantia de renda, faturamento ou enriquecimento. Aprender exige prática, revisão, responsabilidade e atenção às condições reais de cada pessoa.</p></section>`}

function lessonCard(category,index){
 const item=lesson(category,index),key=`${category.id}-${index}`,done=!!readProgress()[key],saved=readEvidence()[key]||{},checks=Array.isArray(saved.checks)?saved.checks:[];
 const ready=checks.filter(Boolean).length===4&&String(saved.production||'').trim().length>=80&&String(saved.test||'').trim().length>=60;
 return `<details class="guide-lesson guide-format-${index%7}" ${index===0?'open':''}><summary><span class="guide-lesson-number">${String(index+1).padStart(2,'0')}</span><span><strong>${e(item.title)}</strong><small>${e(item.module)} · ${e(item.format.name)}</small></span><span class="guide-lesson-state">${done?'✓':'+'}</span></summary><article class="guide-lesson-body"><p class="guide-introduction">${e(item.introduction)}</p><div class="guide-box"><h4>${e(item.format.actions)} · ${e(item.title)}</h4><ol>${item.steps.map(step=>`<li>${e(step)}</li>`).join('')}</ol></div><div class="guide-two-columns"><div class="guide-box guide-example"><h4>${e(item.format.example)}</h4><p>${e(item.example)}</p></div><div class="guide-box"><h4>${e(item.format.exercise)}</h4><p>${e(item.exercise)}</p></div></div><div class="guide-box"><h4>${e(item.format.deliverable)}</h4><p>${e(item.deliverable)}</p></div><div class="guide-box guide-warning"><h4>${e(item.format.warning)}</h4><p>${e(item.warning)}</p></div><section class="guide-proof"><div class="guide-proof-title"><div><span>VERIFICAÇÃO DE EXECUÇÃO</span><h4>${e(item.format.checklist)}</h4></div><b>${done?'Concluída':ready?'Pronta para concluir':'Pendente'}</b></div><div class="guide-proof-checks">${item.checklist.map((check,i)=>`<label class="guide-proof-check"><input type="checkbox" data-guide-check="${e(key)}" data-guide-check-index="${i}" ${checks[i]?'checked':''} ${done?'disabled':''}><span>${e(check)}</span></label>`).join('')}</div><div class="guide-proof-grid"><label><span>O que você produziu nesta aula?</span><textarea data-guide-production="${e(key)}" minlength="80" ${done?'disabled':''} placeholder="Descreva a produção com detalhes verificáveis (mínimo de 80 caracteres).">${e(saved.production||'')}</textarea><small data-guide-production-count="${e(key)}">${String(saved.production||'').trim().length}/80 caracteres</small></label><label><span>Como você testou e qual resultado observou?</span><textarea data-guide-test="${e(key)}" minlength="60" ${done?'disabled':''} placeholder="Registre o teste realizado e o resultado observado (mínimo de 60 caracteres).">${e(saved.test||'')}</textarea><small data-guide-test-count="${e(key)}">${String(saved.test||'').trim().length}/60 caracteres</small></label></div><p class="guide-proof-status ${ready||done?'ready':''}" data-guide-status="${e(key)}">${done?'Aula concluída com evidências registradas.':ready?'Evidências completas. Agora você pode concluir a aula.':'Marque os 4 critérios e preencha os dois registros para liberar a conclusão.'}</p></section><div class="guide-lesson-actions"><button class="primary guide-primary" data-guide-complete="${e(key)}" ${!done&&!ready?'disabled':''}>${done?`Reabrir ${e(item.title)}`:`Concluir ${e(item.title)}`}</button><button class="secondary" data-guide-copy="${e(category.id)}:${index}">Copiar ${e(item.title)}</button></div></article></details>`
}

function categoryView(category){const progress=readProgress(),done=category.topics.filter((_,index)=>progress[`${category.id}-${index}`]).length;return `<button class="guide-back" data-guide-home>← Voltar aos 14 diretórios</button><section class="guide-category-hero"><div class="guide-category-icon">${e(category.icon)}</div><div><p class="eyebrow">ONTOP · DIRETÓRIO GUIADO</p><h2>${e(category.title)}</h2><p>${e(category.description)}</p></div><div class="guide-category-progress"><strong>${done}/30</strong><span>aulas concluídas</span></div></section><div class="guide-progress-bar"><i style="width:${Math.round(done/30*100)}%"></i></div>${category.modules.map((module,moduleIndex)=>`<section class="guide-module"><div class="guide-module-heading"><p class="eyebrow">MÓDULO ${moduleIndex+1}</p><h3>${e(module)}</h3><p>${e(levels[moduleIndex])}</p></div>${category.topics.slice(moduleIndex*10,moduleIndex*10+10).map((_,i)=>lessonCard(category,moduleIndex*10+i)).join('')}</section>`).join('')}${category.id==='ai'?'<div class="guide-ai-link"><button class="primary guide-primary" id="guide-open-ai-library">Abrir as 12 IAs e os 1.200 prompts</button></div>':''}<section class="guide-ethics"><strong>Importante</strong><p>Resultados dependem de contexto, prática, qualidade da entrega e condições reais. Não há garantia de renda ou enriquecimento.</p></section>`}

function navigate(id){const content=document.querySelector('#content');if(!content)return;const category=directories.find(item=>item.id===id);content.innerHTML=category?categoryView(category):home();const title=document.querySelector('#page-title');if(title)title.textContent=category?category.title:'Central de aprendizado';const bread=document.querySelector('#breadcrumb');if(bread)bread.textContent='ONTOP • APRENDA E APLIQUE';document.querySelectorAll('.nav-btn').forEach(button=>button.classList.toggle('active',button.dataset.guideNav===(id||'home')));document.querySelector('#sidebar')?.classList.remove('open');bindGuide();window.scrollTo({top:0,behavior:'smooth'})}

function evidenceReady(key){const saved=readEvidence()[key]||{},checks=Array.isArray(saved.checks)?saved.checks:[];return checks.filter(Boolean).length===4&&String(saved.production||'').trim().length>=80&&String(saved.test||'').trim().length>=60}

function refreshEvidence(key){
 const saved=readEvidence()[key]||{},checks=Array.isArray(saved.checks)?saved.checks:[],ready=evidenceReady(key),done=!!readProgress()[key];
 const productionLength=String(saved.production||'').trim().length,testLength=String(saved.test||'').trim().length;
 const complete=document.querySelector(`[data-guide-complete="${key}"]`),status=document.querySelector(`[data-guide-status="${key}"]`);
 const productionCount=document.querySelector(`[data-guide-production-count="${key}"]`),testCount=document.querySelector(`[data-guide-test-count="${key}"]`);
 if(productionCount)productionCount.textContent=`${productionLength}/80 caracteres`;
 if(testCount)testCount.textContent=`${testLength}/60 caracteres`;
 if(complete)complete.disabled=!done&&!ready;
 if(status){status.classList.toggle('ready',ready||done);status.textContent=done?'Aula concluída com evidências registradas.':ready?'Evidências completas. Agora você pode concluir a aula.':`${checks.filter(Boolean).length}/4 critérios · produção ${Math.min(productionLength,80)}/80 · teste ${Math.min(testLength,60)}/60`;}
}

function bindGuide(){
 document.querySelectorAll('[data-guide-category]').forEach(button=>button.onclick=()=>navigate(button.dataset.guideCategory));
 document.querySelectorAll('[data-guide-home]').forEach(button=>button.onclick=()=>navigate());
 document.querySelectorAll('[data-guide-check]').forEach(input=>input.onchange=()=>{const evidence=readEvidence(),key=input.dataset.guideCheck,saved=evidence[key]||{checks:[],production:'',test:''};saved.checks=Array.isArray(saved.checks)?saved.checks:[];saved.checks[+input.dataset.guideCheckIndex]=input.checked;evidence[key]=saved;writeEvidence(evidence);refreshEvidence(key)});
 document.querySelectorAll('[data-guide-production],[data-guide-test]').forEach(input=>input.oninput=()=>{const key=input.dataset.guideProduction||input.dataset.guideTest,evidence=readEvidence(),saved=evidence[key]||{checks:[],production:'',test:''};if(input.dataset.guideProduction)saved.production=input.value;else saved.test=input.value;evidence[key]=saved;writeEvidence(evidence);refreshEvidence(key)});
 document.querySelectorAll('[data-guide-complete]').forEach(button=>button.onclick=()=>{const key=button.dataset.guideComplete,progress=readProgress(),wasDone=!!progress[key];if(!wasDone&&!evidenceReady(key)){refreshEvidence(key);return}progress[key]=!wasDone;writeProgress(progress);navigate(key.split('-')[0])});
 document.querySelectorAll('[data-guide-copy]').forEach(button=>button.onclick=async()=>{const [id,index]=button.dataset.guideCopy.split(':');const category=directories.find(item=>item.id===id);const item=lesson(category,+index);const output=[item.title,item.introduction,item.format.actions.toUpperCase()+':',...item.steps.map((step,i)=>`${i+1}. ${step}`),item.format.example.toUpperCase()+':',item.example,item.format.exercise.toUpperCase()+':',item.exercise,item.format.deliverable.toUpperCase()+':',item.deliverable,item.format.warning.toUpperCase()+':',item.warning].join('\n');try{await navigator.clipboard.writeText(output);button.textContent='Resumo copiado!'}catch{button.textContent='Não foi possível copiar'}});
 const ai=document.querySelector('#guide-open-ai-library');if(ai)ai.onclick=()=>document.querySelector('#academy-link')?.click()
}

function addNavigation(){const nav=document.querySelector('#nav');if(!nav||document.querySelector('#ontop-guide-navigation'))return;const wrapper=document.createElement('div');wrapper.id='ontop-guide-navigation';wrapper.innerHTML=`<button class="nav-btn guide-nav-home" data-guide-nav="home"><span>◇</span> Aprendizado</button>`;nav.append(wrapper);wrapper.querySelector('[data-guide-nav]').onclick=()=>navigate()}

if(typeof document!=='undefined'){new MutationObserver(addNavigation).observe(document.body,{childList:true,subtree:true});addNavigation();window.OnTopGuide={directories,navigate,lesson}}
