import crypto from 'node:crypto';import {getJson,setJson,configured} from './_store.js';import {json,cors,adminAuthorized} from './_security.js';
const KEY='config:products';
const LEGACY_PRODUCTS=[
 {id:'inicio',tier:'INÍCIO',title:'3 Caminhos para Construir Patrimônio',price:'R$ 19,90',shortDescription:'O primeiro passo para escolher uma direção, organizar suas metas e começar com responsabilidade.',description:'O primeiro passo para escolher uma direção, organizar suas metas e começar com responsabilidade.',url:'https://pay.kiwify.com.br/Mmatzen',cover:'https://raw.githubusercontent.com/andreyribeiro392-coder/ontop-links/main/assets/inicio.png',benefits:['2 e-books práticos','Teste para escolher seu caminho','Plano de ação de 7 dias','Planilha de orçamento e metas'],visible:true},
 {id:'premium',tier:'PREMIUM',title:'Planejamento em Execução',price:'R$ 47,00',shortDescription:'Um pacote completo de ferramentas para transformar ideias em ações organizadas.',description:'Um pacote completo de ferramentas para transformar ideias em ações organizadas.',url:'https://pay.kiwify.com.br/AI0CBXl',cover:'https://raw.githubusercontent.com/andreyribeiro392-coder/ontop-links/main/assets/premium.png',benefits:['6 e-books completos','100 prompts de inteligência artificial','Calendário de conteúdo para 30 dias','Planilhas e modelos profissionais'],badge:'MAIS ESCOLHIDO',featured:true,visible:true},
 {id:'plus',tier:'PLUS',title:'Método OnTop Completo',price:'R$ 97,00',shortDescription:'A estrutura avançada da OnTop para estudar, planejar, produzir e acompanhar sua evolução.',description:'A estrutura avançada da OnTop para estudar, planejar, produzir e acompanhar sua evolução.',url:'https://pay.kiwify.com.br/VYMq2vz',cover:'https://raw.githubusercontent.com/andreyribeiro392-coder/ontop-links/main/assets/plus.png',benefits:['Central Plus com 14 trilhas de aprendizado','12 diretórios de IA com 1.200 prompts','Ferramentas de organização, projetos e CRM','Jornada prática de 90 dias'],badge:'MAIS COMPLETO',visible:true}
];
const clean=(value,max=1000)=>String(value||'').trim().slice(0,max);
const cleanUrl=value=>{const text=clean(value,2000);if(!text)return '';try{const url=new URL(text);return ['http:','https:'].includes(url.protocol)?url.href:''}catch{return ''}};
function normalize(item,current={}){return {id:clean(item.id,80)||current.id||crypto.randomUUID(),tier:clean(item.tier,40),title:clean(item.title,120),price:clean(item.price,40),salePrice:clean(item.salePrice,40),shortDescription:clean(item.shortDescription,260),description:clean(item.description,4000),url:cleanUrl(item.url),cover:cleanUrl(item.cover),images:(Array.isArray(item.images)?item.images:[]).map(cleanUrl).filter(Boolean).slice(0,8),benefits:(Array.isArray(item.benefits)?item.benefits:[]).map(value=>clean(value,180)).filter(Boolean).slice(0,20),badge:clean(item.badge,50),featured:Boolean(item.featured),visible:item.visible!==false,createdAt:current.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};}
export default async function handler(req,res){cors(req,res);if(req.method==='OPTIONS')return json(res,204,{});if(!configured())return json(res,503,{error:'Banco de dados não configurado.'});try{let products=(await getJson(KEY))||[];if(!products.length){products=LEGACY_PRODUCTS.map(item=>normalize(item));await setJson(KEY,products);}if(req.method==='GET')return json(res,200,{products:adminAuthorized(req)?products:products.filter(p=>p.visible)});if(!adminAuthorized(req))return json(res,401,{error:'Senha administrativa incorreta.'});if(req.method==='POST'){const product=normalize(req.body||{});if(!product.title||!product.url)return json(res,400,{error:'Preencha o título e o link do produto.'});products.unshift(product);await setJson(KEY,products.slice(0,200));return json(res,201,{ok:true,product});}if(req.method==='PATCH'){const index=products.findIndex(p=>p.id===req.body?.id);if(index<0)return json(res,404,{error:'Produto não encontrado.'});const product=normalize(req.body,products[index]);if(!product.title||!product.url)return json(res,400,{error:'Preencha o título e o link do produto.'});products[index]=product;await setJson(KEY,products);return json(res,200,{ok:true,product});}if(req.method==='DELETE'){const id=clean(req.body?.id,80);const next=products.filter(p=>p.id!==id);if(next.length===products.length)return json(res,404,{error:'Produto não encontrado.'});await setJson(KEY,next);return json(res,200,{ok:true});}return json(res,405,{error:'Método não permitido'});}catch(e){console.error(e);return json(res,500,{error:'Não foi possível atualizar o catálogo.'});}}
